# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Erlang Ecosystem Foundation

on:
  workflow_call: {}

name: "Rebar3 Dependency Submission"

permissions:
  contents: read

jobs:
  submit:
    name: "Submit"

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: erlef/rebar3-dependency-submission@0cdde3e058a8d76db523f4632562b7e15095efbf # v0.1.2
